-- Table TAI_KHOAN
CREATE TABLE [dbo].[TAI_KHOAN](
	[MaTK] INT IDENTITY(1,1) NOT NULL,
	[SDT] NVARCHAR(20) UNIQUE NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	PRIMARY KEY CLUSTERED ([MaTK] ASC)
)
GO

-- Table CONG_VIEC
CREATE TABLE [dbo].[CONG_VIEC](
	[MaCV] INT IDENTITY(1,1) NOT NULL,
	[TenCV] NVARCHAR(100) NOT NULL,
	[Luong] INT CHECK ([Luong] > 0) NOT NULL,
	PRIMARY KEY CLUSTERED ([MaCV] ASC)
)
GO

-- Table NHA_SAN_XUAT
CREATE TABLE [dbo].[NHA_SAN_XUAT](
	[MaNSX] INT IDENTITY(1,1) NOT NULL,
	[TenNSX] NVARCHAR(100) NOT NULL,
	[SDT] NVARCHAR(20) NOT NULL,
	[Email] NVARCHAR(100) NULL,
	PRIMARY KEY CLUSTERED ([MaNSX] ASC)
)
GO

-- Table KHACH_HANG
CREATE TABLE [dbo].[KHACH_HANG](
	[MaKH] INT IDENTITY(1,1) NOT NULL,
	[HoTen] NVARCHAR(100) NOT NULL,
	[DiaChi] NVARCHAR(255) NOT NULL,
	[SDT] NVARCHAR(20) NOT NULL,
	[Email] NVARCHAR(100) NULL,
	[MaTK] INT NULL,
	PRIMARY KEY CLUSTERED ([MaKH] ASC)
)
GO

ALTER TABLE [dbo].[KHACH_HANG] 
ADD CONSTRAINT [FK_KHACH_HANG_TAI_KHOAN] FOREIGN KEY ([MaTK]) REFERENCES [dbo].[TAI_KHOAN] ([MaTK])
GO

-- Table NHAN_VIEN
CREATE TABLE [dbo].[NHAN_VIEN](
	[MaNV] INT IDENTITY(1,1) NOT NULL,
	[HoTen] NVARCHAR(100) NOT NULL,
	[NgaySinh] DATE NOT NULL,
	[GioiTinh] NVARCHAR(10) NOT NULL,
	[SDT] NVARCHAR(20) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[DiaChi] NVARCHAR(255) NOT NULL,
	[MaCV] INT NULL,
	[MaTK] INT NULL,
	PRIMARY KEY CLUSTERED ([MaNV] ASC)
)
GO

ALTER TABLE [dbo].[NHAN_VIEN] 
ADD CONSTRAINT [FK_NHAN_VIEN_CONG_VIEC] FOREIGN KEY ([MaCV]) REFERENCES [dbo].[CONG_VIEC] ([MaCV])
GO

ALTER TABLE [dbo].[NHAN_VIEN] 
ADD CONSTRAINT [FK_NHAN_VIEN_TAI_KHOAN] FOREIGN KEY ([MaTK]) REFERENCES [dbo].[TAI_KHOAN] ([MaTK])
GO

-- Table SAN_PHAM
CREATE TABLE [dbo].[SAN_PHAM](
	[MaSP] INT IDENTITY(1,1) NOT NULL,
	[TenSP] NVARCHAR(100) NOT NULL,
	[Gia] INT NOT NULL,
	[SoLuong] INT DEFAULT (0) NOT NULL,
	[TinhTrang] NVARCHAR(50) NOT NULL,
	PRIMARY KEY CLUSTERED ([MaSP] ASC)
)
GO

-- Table DON_HANG
CREATE TABLE [dbo].[DON_HANG](
	[MaDH] INT IDENTITY(1,1) NOT NULL,
	[NgayDatHang] DATETIME NOT NULL,
	[TrangThaiDonHang] NVARCHAR(50) NOT NULL,
	[TriGia] INT NOT NULL,
	[MaUngDung] INT NULL,
	[MaKH] INT NULL,
	PRIMARY KEY CLUSTERED ([MaDH] ASC)
)
GO

ALTER TABLE [dbo].[DON_HANG] 
ADD CONSTRAINT [FK_DON_HANG_KHACH_HANG] FOREIGN KEY ([MaKH]) REFERENCES [dbo].[KHACH_HANG] ([MaKH])
GO

-- Table UNG_DUNG
CREATE TABLE [dbo].[UNG_DUNG](
	[MaUngDung] INT IDENTITY(1,1) NOT NULL,
	[TenUngDung] NVARCHAR(100) NOT NULL,
	[ChietKhau] INT NOT NULL,
	PRIMARY KEY CLUSTERED ([MaUngDung] ASC)
)
GO

ALTER TABLE [dbo].[DON_HANG] 
ADD CONSTRAINT [FK_DON_HANG_UNG_DUNG] FOREIGN KEY ([MaUngDung]) REFERENCES [dbo].[UNG_DUNG] ([MaUngDung]) ON DELETE SET NULL
GO

-- Table DON_NHAP_HANG
CREATE TABLE [dbo].[DON_NHAP_HANG](
	[MaDon] INT IDENTITY(1,1) NOT NULL,
	[NgayNhap] DATETIME NOT NULL,
	[GiaTri] INT NOT NULL,
	[SoLuong] INT NOT NULL,
	[DonGia] INT NOT NULL,
	[MaSP] INT NOT NULL,
	[MaNSX] INT NULL,
	PRIMARY KEY CLUSTERED ([MaDon] ASC)
)
GO

ALTER TABLE [dbo].[DON_NHAP_HANG] 
ADD CONSTRAINT [FK_DON_NHAP_HANG_NHA_SAN_XUAT] FOREIGN KEY ([MaNSX]) REFERENCES [dbo].[NHA_SAN_XUAT] ([MaNSX]) ON DELETE SET NULL
GO

ALTER TABLE [dbo].[DON_NHAP_HANG] 
ADD CONSTRAINT [FK_DON_NHAP_HANG_SAN_PHAM] FOREIGN KEY ([MaSP]) REFERENCES [dbo].[SAN_PHAM] ([MaSP]) ON DELETE CASCADE
GO

-- Table CA_LAM_VIEC
CREATE TABLE [dbo].[CA_LAM_VIEC](
	[MaCa] INT IDENTITY(1,1) NOT NULL,
	[MaNV] INT NOT NULL,
	[ThoiGianBatDau] DATETIME NOT NULL,
	[ThoiGianKetThuc] DATETIME NOT NULL,
	PRIMARY KEY CLUSTERED ([MaCa] ASC)
)
GO

ALTER TABLE [dbo].[CA_LAM_VIEC] 
ADD CONSTRAINT [FK_CA_LAM_VIEC_NHAN_VIEN] FOREIGN KEY ([MaNV]) REFERENCES [dbo].[NHAN_VIEN] ([MaNV])
GO

-- Table SAN_PHAM_DUOC_CHON
CREATE TABLE [dbo].[SAN_PHAM_DUOC_CHON](
	[MaSPDonHang] INT IDENTITY(1,1) NOT NULL,
	[SoLuong] INT NOT NULL,
	[DonGia] INT NOT NULL,
	[MaSP] INT NULL,
	[MaDH] INT NOT NULL,
	PRIMARY KEY CLUSTERED ([MaSPDonHang] ASC)
)
GO

ALTER TABLE [dbo].[SAN_PHAM_DUOC_CHON] 
ADD CONSTRAINT [FK_SAN_PHAM_DUOC_CHON_DON_HANG] FOREIGN KEY ([MaDH]) REFERENCES [dbo].[DON_HANG] ([MaDH])
GO

ALTER TABLE [dbo].[SAN_PHAM_DUOC_CHON] 
ADD CONSTRAINT [FK_SAN_PHAM_DUOC_CHON_SAN_PHAM] FOREIGN KEY ([MaSP]) REFERENCES [dbo].[SAN_PHAM] ([MaSP]) ON DELETE SET NULL
GO

-- Table THANH_TOAN
CREATE TABLE [dbo].[THANH_TOAN](
	[MaDH] INT NOT NULL,
	[MaKH] INT NOT NULL,
	[DaThanhToan] BIT NULL,
	PRIMARY KEY CLUSTERED ([MaDH] ASC, [MaKH] ASC)
)
GO

ALTER TABLE [dbo].[THANH_TOAN] 
ADD CONSTRAINT [FK_THANH_TOAN_DON_HANG] FOREIGN KEY ([MaDH]) REFERENCES [dbo].[DON_HANG] ([MaDH])
GO

ALTER TABLE [dbo].[THANH_TOAN] 
ADD CONSTRAINT [FK_THANH_TOAN_KHACH_HANG] FOREIGN KEY ([MaKH]) REFERENCES [dbo].[KHACH_HANG] ([MaKH])
GO
